export const allAnimations = [
  {
    id: "1",
    title: "Quantum Superposition",
    category: "Physics",
    code: "",
    level: "Advanced",
    likes: 342,
    comments: 56,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.7,
    ratingCount: 243,
    description:
      "Explore the fascinating world of quantum mechanics through this interactive animation explaining how particles can exist in multiple states simultaneously until measured.",
  },
  {
    id: "2",
    title: "Neural Networks Explained",
    category: "Computer Science",
    code: "",
    level: "Advanced",
    likes: 289,
    comments: 42,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 9.2,
    ratingCount: 187,
    description:
      "Understand how artificial neural networks function by mimicking the human brain. This animation breaks down complex concepts into simple visual explanations.",
  },
  {
    id: "3",
    title: "Fourier Transforms",
    category: "Mathematics",
    code: "",
    level: "Advanced",
    likes: 256,
    comments: 38,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 7.8,
    ratingCount: 156,
    description:
      "Visualize how Fourier transforms convert signals between time and frequency domains, a fundamental concept in signal processing and data analysis.",
  },
  {
    id: "4",
    title: "Cognitive Dissonance",
    category: "Psychology",
    level: "Advanced",
    code: "",
    likes: 198,
    comments: 27,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.3,
    ratingCount: 112,
    description:
      "Discover how conflicting beliefs create psychological discomfort and how humans resolve these internal conflicts through various mental strategies.",
  },
  {
    id: "5",
    title: "Blockchain Technology",
    category: "Computer Science",
    level: "Advanced",
    code: "",
    likes: 176,
    comments: 31,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 9.5,
    ratingCount: 98,
    description:
      "Learn how blockchain creates secure, decentralized record-keeping through this step-by-step animation of transactions, blocks, and consensus mechanisms.",
  },
  {
    id: "6",
    title: "Chaos Theory",
    category: "Mathematics",
    level: "Advanced",
    code: "",
    likes: 221,
    comments: 35,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.9,
    ratingCount: 132,
    description:
      "Explore how small changes in initial conditions can lead to vastly different outcomes in deterministic systems, illustrated through captivating visual examples.",
  },
  {
    id: "7",
    title: "Relativity Simplified",
    category: "Physics",
    level: "Advanced",
    code: "",
    likes: 312,
    comments: 48,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 9.3,
    ratingCount: 215,
    description:
      "Einstein's theories of relativity explained through intuitive animations that demonstrate how space, time, and gravity are interconnected in our universe.",
  },
  {
    id: "8",
    title: "Game Theory Basics",
    category: "Mathematics",
    level: "Advanced",
    code: "",
    likes: 187,
    comments: 29,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.6,
    ratingCount: 143,
    description:
      "Understand strategic decision-making through interactive examples of classic game theory scenarios like the Prisoner's Dilemma and Nash Equilibrium.",
  },
  {
    id: "9",
    title: "String Theory Explained",
    category: "Physics",
    level: "Advanced",
    code: "",
    likes: 124,
    comments: 18,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 7.9,
    ratingCount: 42,
    description:
      "Dive into the theoretical framework where one-dimensional strings replace point-like particles as the fundamental building blocks of the universe.",
  },
  {
    id: "10",
    title: "Cryptography Fundamentals",
    category: "Computer Science",
    level: "Advanced",
    code: "",
    likes: 156,
    comments: 23,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.2,
    ratingCount: 67,
    description:
      "Learn the principles of secure communication through visual demonstrations of encryption algorithms, key exchange methods, and digital signatures.",
  },
  {
    id: "11",
    title: "Behavioral Economics",
    category: "Economics",
    level: "Advanced",
    code: "",
    likes: 98,
    comments: 14,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 8.0,
    ratingCount: 35,
    description:
      "Explore how psychological, social, and emotional factors influence economic decisions, challenging traditional models of rational economic behavior.",
  },
  {
    id: "12",
    title: "Topology Basics",
    category: "Mathematics",
    level: "Advanced",
    code: "",
    likes: 112,
    comments: 19,
    thumbnail: "/placeholder.svg?height=200&width=350",
    averageRating: 7.5,
    ratingCount: 28,
    description:
      "Discover the mathematical study of shapes and spaces that are preserved under continuous deformations, from simple Möbius strips to complex manifolds.",
  },
];
